POST http://localhost:3333/api/links
Content-Type: application/json

{
    "code": "TEST",
    "url": "https://www.linkedin.com/in/devsamuelsouza/"
}

###

GET http://localhost:3333/api/links

###

GET http://localhost:3333/smkdev
