POST http://localhost:3333/api/links
Content-Type: application/json

{
    "code": "rocket",
    "url": "https://app.rocketseat.com.br/home"
}

###

GET http://localhost:3333/api/links

###

GET http://localhost:3333/TEST
###

GET http://localhost:3333/api/metrics
